import type { Metadata, Viewport } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Simple Web-Push app',
  description: 'Generated by create next app',
  themeColor: '#111827',
  manifest: '/manifest.webmanifest',
  icons: {
    icon: '/next.png',
    apple: '/next.png',
  },
};

// Add viewport configuration for PWA
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
  themeColor: '#111827',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/next.png" type="image/png" />
        <link rel="apple-touch-icon" href="/next.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="Web Push" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
